#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ssd-detection','console_scripts','detection_example'
__requires__ = 'ssd-detection'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ssd-detection', 'console_scripts', 'detection_example')()
    )
